version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  join:
    lang: python3-http
    handler: ./join
    image: alexellisuk/join:latest-0.1
    environment:
      FLASK_ENV: development
